language: php

php:
  - '7.0'
  - '7.2'

git:
  depth: 10
  submodules: false

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.composer/cache
    - $HOME/.npm

install:
  - composer install --prefer-dist --no-interaction
  - pecl install ast-1.0.0

script:
  - vendor/bin/phpcs -n
  - vendor/bin/phan
  - vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode9.1
      language: generic
      before_install:
        # Fix ruby error https://github.com/Homebrew/brew/issues/3299
        - brew update
        - brew install php@7.1
        - brew link --force --overwrite php@7.1
        - pecl install xdebug-2.6.0
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - ln -s "`pwd`/composer.phar" /usr/local/bin/composer
    - stage: release
      php: '7.0'
      services:
        - docker
      install:
        - nvm install 8
        - nvm use 8
        - npm install
      script:
        - ./node_modules/.bin/semantic-release

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  only:
    - master
